FROM sonarqube:7.1
EXPOSE 9443
EXPOSE 9000
RUN apt-get update 
RUN apt-get install -y wget curl net-tools nginx vim
COPY nginx-sonar /etc/nginx/sites-enabled/nginx-sonar
COPY localsite.key /etc/ssl/localsite.key
COPY localsite.crt /etc/ssl/localsite.crt
COPY run.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/run.sh
ENTRYPOINT ["run.sh"]
